In [4]:
#44 рассмотрtnm случайную матрицу размером 10х2, представляющую декартовы координаты, преобразуем их в полярные координаты
import numpy as np
a = np.random.randn(10, 2)  # 10 точек, каждая имеет (x, y)

print("Декартовы координаты (x, y):")
print(a)

# Преобразуем в полярные координаты (r, phi)
# r = sqrt(x^2 + y^2)
# phi = arctan2(y, x) - угол в радианах от -pi до pi
r = np.sqrt(a[:, 0]**2 + a[:, 1]**2)
phi = np.arctan2(a[:, 1], a[:, 0])

# Собираем полярные координаты в матрицу
polar_coords = np.column_stack((r, phi)) #np.column_stack — объединяет одномерные массивы в виде столбцов в двумерный массив.
#Преобразуем радианы в градусы для наглядности
phi_degrees = np.degrees(phi)
polar_coords_degrees = np.column_stack((r, phi_degrees))
print(polar_coords_degrees)

Декартовы координаты (x, y):
[[ 0.73846658  0.17136828]
 [-0.11564828 -0.3011037 ]
 [-1.47852199 -0.71984421]
 [-0.46063877  1.05712223]
 [ 0.34361829 -1.76304016]
 [ 0.32408397 -0.38508228]
 [-0.676922    0.61167629]
 [ 1.03099952  0.93128012]
 [-0.83921752 -0.30921238]
 [ 0.33126343  0.97554513]]
[[   0.75808969   13.06479308]
 [   0.32254916 -111.01084614]
 [   1.6444461  -154.04005755]
 [   1.15312423  113.54506263]
 [   1.79621383  -78.97125559]
 [   0.50330784  -49.91614597]
 [   0.91234384  137.89858693]
 [   1.38933174   42.09083757]
 [   0.89437036 -159.77351917]
 [   1.03025422   71.24418174]]


In [ ]:
#1 Импортируйте пакет numpy под именем np
import numpy as np

In [5]:
#2 Распечатайте версию numpy и конфигурацию 
import numpy as np
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Ksenya_work/anaconda3/Library/include
    lib directory: C:/Users/Ksenya_work/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: window

In [10]:
#3 Создайте нулевой вектор размером 10
import numpy as np
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#4 Как определить объем памяти любого массива
arr = np.random.rand(10, 5)  
print(f"Общий объем памяти: {arr.nbytes} байт")
print(f"Общий объем памяти: {arr.nbytes / 1024:.2f} КБ")
print(f"Общий объем памяти: {arr.nbytes / (1024**2):.2f} МБ")

(10, 5)
Тип данных: float64
Общий объем памяти: 400 байт
Общий объем памяти: 0.39 КБ
Общий объем памяти: 0.00 МБ


In [16]:
#6  Создайте нулевой вектор размером 10, но с пятым значением, равным 1 
import numpy as np
zero_vector = np.zeros(10)
zero_vector[4] = 1
print(zero_vector)
print(int(zero_vector[4]))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
1


In [20]:
#7  Создайте вектор со значениями в диапазоне от 10 до 49
import numpy as np
vector = np.array(range(10,50))
print(vector)
print(vector[24])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
34


In [27]:
#8 Изменить вектор (первый элемент становится последним)
import numpy as np
vector = np.array(range(1,11))
vector_changes = np.concatenate([vector[1:],vector[0:1]]) # np.concatenate - объединяет массивы
print (vector_changes)

[ 2  3  4  5  6  7  8  9 10  1]


In [30]:
# 9 Создайте матрицу размером 3х3 со значениями в диапазоне от 0 до 8 
import numpy as np
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#10 Найти индексы ненулевых элементов из [1,2,0,0,4,0]
a = np.array([1,2,0,0,4,0])
indexes = np.flatnonzero(a)
print(indexes)

[0 1 4]


In [36]:
# 11 Создайте массив размером 3х3х3 со случайными значениями
import numpy as np
a = np.random.rand(3,3,3)
print(a)

[[[0.11986537 0.33761517 0.9429097 ]
  [0.32320293 0.51879062 0.70301896]
  [0.3636296  0.97178208 0.96244729]]

 [[0.2517823  0.49724851 0.30087831]
  [0.28484049 0.03688695 0.60956433]
  [0.50267902 0.05147875 0.27864646]]

 [[0.90826589 0.23956189 0.14489487]
  [0.48945276 0.98565045 0.24205527]
  [0.67213555 0.76161962 0.23763754]]]
